### ISSUE TITLE
Question on production case

### ISSUE THREAD

**Issue by 333miiko** [Alphafluffykitten/fledger#1]
Hi, 

Really cool that you made this. I was wondering are you using this in production? 

I've always been stuck thinking about whats the best way to calculate balance. I notice just like Medici you use a "cached" balance table. Have you considered how this gets effected by race conditions? if there were two processes inserting at the same time, what were your considerations over using cached balance vs perhaps a materalised view? (would it not scale)

Curious as considering both products are inspired by Medici, was there a reason you built fledger compared to using this existing one https://github.com/CjS77/ale

Want to make sure I start off with the right foundation

Appreciate your help :)

**Comment by Alphafluffykitten** [comment]
Hi!

Yes, I'm using it in production, in fact, I wrote it cuz I needed a multi-currency solution for my own project. It has worked pretty well for several months now, fast and without any issues.

> I notice just like Medici you use a "cached" balance table. Have you considered how this gets effected by race conditions?

In principle, it can get affected by race conditions. Currently, there is no protection against it.
It can happen this way (consider processes P1 and P2):
```
               - P1 queries for balance
               - P1 checks cache row
               - P1 checks for new txs after cache row (no new txs at the moment)
P2 adds new tx - 
               - P1 doesn't add new txs to the cache table
               - P1 returns balance (without new tx included)
```

I was considering adding protection, like a lock mechanism that forbids any new txs on queried accounts during the balance query procedure. But now it works as is, my project is low-loaded at the moment, so it doesn't hurt now. Time window for the error is relatively narrow.

On ALE: I remember considering using it, but can't remember the exact reason why I decided to build my own. Probably it was because of its architectural decision - a standalone microservice

**Comment by 333miiko** [comment]
Thanks for your insight, its been super helpful

Have you considered replacing the balance with a view (or even materalised view). That way you're not relying on some "cached" balance which adds risk due to race conditions. A materalised view, while could be stale at least won't have the risk of missing a transaction if two are entered at the same time

I was also thinking this is more of an issue which could be solved by a timeseries database. Perhaps timescaledb (a postgres extension) could be a way to solve this in a much better fashion, keen to hear your thoughts on this.

**Comment by Alphafluffykitten** [comment]
Hi,

Well, since `view` has to refetch all transaction rows upon balance query, it wont be fast. To be fast it has to know underlying logic of balance, which is implemented in fledger balance.

More to that, im not sure if materialized view will not have same vulnerability as implemented fledger balance logic.

To solve this race condition issue, one way is to implement fledger as a standalone container service which blocks tx creation for accounts that are being queried for balance now

About timeseries DB, im not really familiar with it.

Best regards!
